version: "3.8"
services:

  bienesraices_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bienesraices_app
    working_dir: /var/www
    ports:
      - $APP_PORT:8080
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    networks:
      - bienesraices_network

  bienesraices_db:
    image: mysql:5.7
    container_name: bienesraices_db
    restart: unless-stopped
    ports:
      - $DB_PORT:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    volumes:
      - bienesraices_db:/var/lib/mysql
    networks:
      - bienesraices_network

  bienesraices_mailhog:
    image: mailhog/mailhog:latest
    container_name: bienesraices_mailhog
    ports:
      - $MAIL_PORT:1025
      - 8025:8025
    networks:
      - bienesraices_network

volumes:
  bienesraices_db:


networks:
  bienesraices_network:
    name: bienesraices_net
    driver: bridge
    ipam:
      driver: default
